---
- name: "Rcconf:nrpe: Enable and start {{ bsd_nrpe_service }}"
  when: bsd_nrpe_enable | bool
  notify: enable and start nrpe
  ansible.builtin.lineinfile:
    dest: /etc/rc.conf
    regexp: ^\s*{{ bsd_nrpe_service }}_enable\s*=(.*)$
    line: '{{ bsd_nrpe_service }}_enable="YES"'
    backup: "{{ bsd_nagios_backup_conf }}"

- name: "Rcconf:nrpe: Disable and stop {{ bsd_nrpe_service }}"
  when: not bsd_nrpe_enable | bool
  notify: disable and stop nrpe
  ansible.builtin.lineinfile:
    dest: /etc/rc.conf
    regexp: ^\s*{{ bsd_nrpe_service }}_enable\s*=(.*)$
    line: '{{ bsd_nrpe_service }}_enable="NO"'
    backup: "{{ bsd_nagios_backup_conf }}"

- name: "Rcconf:nrpe: Configure nrpe in /etc/rc.conf"
  notify: reload nrpe
  ansible.builtin.lineinfile:
    dest: /etc/rc.conf
    regexp: ^\s*{{ item.key }}\s*=(.*)$
    line: '{{ item.key }}="{{ item.val }}"'
    backup: "{{ bsd_nagios_backup_conf }}"
  loop: "{{ bsd_nrpe_rcconf }}"

# EOF
