---
- name: "Actions: Debug bsd_nagios_debug={{ bsd_nagios_debug }}"
  when: bsd_nagios_debug | bool
  ansible.builtin.debug:
    var: bsd_nagios_actions

- name: "Actions: Nagios downtime and notifications"
  register: result
  community.general.nagios:
    action: "{{ item.action }}"
    author: "{{ item.author | d(omit) }}"
    cmdfile: "{{ item.cmdfile | d(omit) }}"
    command: "{{ item.command | d(omit) }}"
    comment: "{{ item.comment | d(omit) }}"
    host: "{{ item.host | d(omit) }}"
    minutes: "{{ item.minutes | d(omit) }}"
    servicegroup: "{{ item.servicegroup | d(omit) }}"
    services: "{{ item.services | d(omit) }}"
    start: "{{ item.start | d(omit) }}"
  loop: "{{ bsd_nagios_actions }}"
  loop_control:
    label: "{{ item.action }} {{ item.host | d('nohost') }} {{ item.command | d('nocommand') }}"

- name: "Actions: Debug bsd_nagios_debug={{ bsd_nagios_debug }}"
  when: bsd_nagios_debug | bool
  ansible.builtin.debug:
    var: result

# EOF
