---
- name: "Conf: Create config files from samples"
  tags: bsd_nagios_conf_files
  ansible.builtin.import_tasks: conf/nagios_files.yml

- name: "Conf: Configure options"
  tags: bsd_nagios_conf_options
  ansible.builtin.import_tasks: conf/nagios_options.yml

- name: "Conf: Configure cfg_file in nagios.cfg"
  tags: bsd_nagios_conf_cfg_file
  ansible.builtin.import_tasks: conf/nagios_cfg_file.yml

- name: "Conf: Configure cfg_dir in nagios.cfg"
  tags: bsd_nagios_conf_cfg_dir
  ansible.builtin.import_tasks: conf/nagios_cfg_dir.yml

# EOF
