---

- name: "nagios: Remove config files."
  file:
    path: "{{ item }}"
    state: absent
  loop: "{{ bsd_nagios_conf_files }}"
  when: bsd_nagios_conf_recreate

- name: "nagios: Create config files."
  include_tasks: nagios-create-conf.yml
  loop: "{{ bsd_nagios_conf_files }}"

# EOF
...
