---
- name: "Nsca: Create config files from samples"
  tags: bsd_nsca_conf_files
  ansible.builtin.import_tasks: conf/nsca_files.yml

- name: "Nsca: Configure nsca"
  when: item.1.present | d(true)
  notify: reload nsca
  ansible.builtin.lineinfile:
    dest: "{{ item.0.file }}"
    regexp: ^\s*#*\s*{{ item.1.key }}
    line: "{{ item.1.key }}={{ item.1.val }}"
    backup: "{{ bsd_nagios_backup_conf }}"
  loop: "{{ bsd_nsca_conf_options | subelements('conf') }}"
  loop_control:
    label: "{{ item.0.file }} {{ item.1.key }}={{ item.1.val }}"

- name: "Conf:nsca: Remove nsca configuration items"
  when: not item.1.present | d(true)
  notify: reload nsca
  ansible.builtin.lineinfile:
    dest: "{{ item.0.file }}"
    regexp: ^\s*#*\s*{{ item.1.key }}(.*)$
    line: "# {{ item.1.key }}\\g<1>"
    backup: "{{ bsd_nagios_backup_conf }}"
  loop: "{{ bsd_nsca_conf_options | subelements('conf') }}"
  loop_control:
    label: "{{ item.0.file }} {{ item.1.key }}"

# EOF
