---
- name: Import rcconf/nagios.yml
  ansible.builtin.import_tasks: rcconf/nagios.yml

- name: Import rcconf/nsca.yml
  when: bsd_nrpe | bool
  ansible.builtin.import_tasks: rcconf/nsca.yml

- name: Import rcconf/nrpe.yml
  when: bsd_nsca | bool
  ansible.builtin.import_tasks: rcconf/nrpe.yml

# EOF
