---
# verify and reload nagios handler freebsd_nagios

- name: verify nagios
  command: "{{ bsd_nagios_program }} -v {{ bsd_nagios_conf_path }}/nagios.cfg"

- name: reload nagios
  service:
    name: "{{ bsd_nagios_service }}"
    state: reloaded
  when: bsd_nagios_enable

# EOF
...
