---
# nrpe handlers freebsd_nagios

- name: Enable and start nrpe
  ansible.builtin.service:
    name: "{{ bsd_nrpe_service }}"
    state: started
    enabled: true

- name: Disable and stop nrpe
  ansible.builtin.service:
    name: "{{ bsd_nrpe_service }}"
    state: stopped
    enabled: false

- name: Start nrpe
  ansible.builtin.service:
    name: "{{ bsd_nrpe_service }}"
    state: started

- name: Stop nrpe
  ansible.builtin.service:
    name: "{{ bsd_nrpe_service }}"
    state: stopped

- name: Restart nrpe
  ansible.builtin.service:
    name: "{{ bsd_nrpe_service }}"
    state: restarted
  when: bsd_nrpe_enable|bool

- name: Reload nrpe
  ansible.builtin.service:
    name: "{{ bsd_nrpe_service }}"
    state: reloaded
  when: bsd_nrpe_enable|bool

# EOF
