---
# nrpe handlers freebsd_nagios

- name: Enable and start nrpe
  listen: enable and start nrpe
  ansible.builtin.service:
    name: "{{ bsd_nrpe_service }}"
    state: started
    enabled: true

- name: Disable and stop nrpe
  listen: disable and stop nrpe
  ansible.builtin.service:
    name: "{{ bsd_nrpe_service }}"
    state: stopped
    enabled: false

- name: Start nrpe
  listen: start nrpe
  ansible.builtin.service:
    name: "{{ bsd_nrpe_service }}"
    state: started

- name: Stop nrpe
  listen: stop nrpe
  ansible.builtin.service:
    name: "{{ bsd_nrpe_service }}"
    state: stopped

- name: Restart nrpe
  listen: restart nrpe
  when: bsd_nrpe_enable | bool
  ansible.builtin.service:
    name: "{{ bsd_nrpe_service }}"
    state: restarted

- name: Reload nrpe
  listen: reload nrpe
  when: bsd_nrpe_enable | bool
  ansible.builtin.service:
    name: "{{ bsd_nrpe_service }}"
    state: reloaded

# EOF
