---
# nsca handlers freebsd_nagios

- name: Enable and start nsca
  ansible.builtin.service:
    name: "{{ bsd_nsca_service }}"
    state: started
    enabled: true

- name: Disable and stop nsca
  ansible.builtin.service:
    name: "{{ bsd_nsca_service }}"
    state: stopped
    enabled: false

- name: Start nsca
  ansible.builtin.service:
    name: "{{ bsd_nsca_service }}"
    state: started

- name: Stop nsca
  ansible.builtin.service:
    name: "{{ bsd_nsca_service }}"
    state: stopped

- name: Restart nsca
  ansible.builtin.service:
    name: "{{ bsd_nsca_service }}"
    state: restarted
  when: bsd_nsca_enable|bool

- name: Reload nsca
  ansible.builtin.service:
    name: "{{ bsd_nsca_service }}"
    state: reloaded
  when: bsd_nsca_enable|bool

# EOF
