---
# nsca handlers freebsd_nagios

- name: enable and start nsca
  service:
    name: "{{ bsd_nsca_service }}"
    state: started
    enabled: true

- name: disable and stop nsca
  service:
    name: "{{ bsd_nsca_service }}"
    state: stopped
    enabled: false

- name: start nsca
  service:
    name: "{{ bsd_nsca_service }}"
    state: started

- name: stop nsca
  service:
    name: "{{ bsd_nsca_service }}"
    state: stopped

- name: restart nsca
  service:
    name: "{{ bsd_nsca_service }}"
    state: restarted
  when: bsd_nsca_enable|bool

- name: reload nsca
  service:
    name: "{{ bsd_nsca_service }}"
    state: reloaded
  when: bsd_nsca_enable|bool

# EOF
...
