---

- name: "conf:conf-create: Stat {{ item }}"
  stat:
    path: "{{ item }}"
  register: conf_file

- name: "conf:conf-create: Create {{ item }}"
  command: "cp {{ item }}{{ bsd_nagios_conf_sample }} {{ item }}"
  args:
    creates: "{{ item }}"
  when: not conf_file.stat.exists

- name: "conf:conf-create: Chown {{ item }}"
  file:
    path: "{{ item }}"
    owner: "{{ bsd_nagios_conf_owner }}"
    group: "{{ bsd_nagios_conf_group }}"

# EOF
...
