---
- name: "Conf:create_file: Stat {{ item }}"
  ansible.builtin.stat:
    path: "{{ item }}"
  register: conf_file

- name: Create conf file from sample.
  when: not conf_file.stat.exists | d(false)
  vars:
    file_sample: "{{ item }}{{ bsd_nagios_conf_sample }}"
  block:

    # - name: "Conf:create_file: Stat {{ file_sample }}"
    #   ansible.builtin.stat:
    #     path: "{{ file_sample }}"
    #   register: result

    # - name: "Conf:create_file: Debug stat bsd_nagios_debug={{ bsd_nagios_debug }}"
    #   ansible.builtin.debug:
    #     var: result
    #   when: bsd_nagios_debug | bool

    - name: "Conf:create_file: Create {{ item }}"
      ansible.builtin.copy:
        remote_src: true
        src: "{{ file_sample }}"
        dest: "{{ item }}"
        owner: "{{ conf_file_sample.stat.pw_name }}"
        group: "{{ conf_file_sample.stat.gr_name }}"
        mode: preserve

    # Let's keep the samples' ownership and mode
    # TODO: Optionally change ownership and mode
    # - name: "Conf:create: chown {{ item }}"
    #   file:
    #     path: "{{ item }}"
    #     owner: "{{ bsd_nagios_conf_owner }}"
    #     group: "{{ bsd_nagios_conf_group }}"

# EOF
