---
- name: "Conf:create_file: Stat {{ item }}"
  register: conf_file
  ansible.builtin.stat:
    path: "{{ item }}"

- name: Create conf file from sample.
  when: not conf_file.stat.exists | d(false)
  vars:
    file_sample: "{{ item }}{{ bsd_nagios_conf_sample }}"
  block:

    - name: "Conf:create_file: Stat {{ file_sample }}"
      register: result
      ansible.builtin.stat:
        path: "{{ file_sample }}"

    - name: "Conf:create_file: Debug stat bsd_nagios_debug={{ bsd_nagios_debug }}"
      when: bsd_nagios_debug | bool
      ansible.builtin.debug:
        msg: |
          result.stat.pw_name: {{ result.stat.pw_name }}
          result.stat.gr_name: {{ result.stat.gr_name }}

    - name: "Conf:create_file: Create {{ item }}"
      ansible.builtin.copy:
        remote_src: true
        src: "{{ file_sample }}"
        dest: "{{ item }}"
        owner: "{{ result.stat.pw_name }}"
        group: "{{ result.stat.gr_name }}"
        mode: preserve

# EOF
