---

- name: "conf:options: Debug"
  ansible.builtin.debug:
    var: bsd_nagios_conf_options
  when: bsd_nagios_debug|bool

- name: "conf:options: Configure options"
  ansible.builtin.lineinfile:
    dest: "{{ item.0.file }}"
    regexp: '^\s*#*\s*{{ item.1.key }}'
    line: "{{ item.1.key }}={{ item.1.val }}"
    backup: "{{ bsd_nagios_backup_conf }}"
  loop: "{{ bsd_nagios_conf_options|subelements('conf') }}"
  loop_control:
    label: "{{ item.0.file }} {{ item.1.key }}={{ item.1.val }}"
  when: item.1.present|default(true)|bool
  notify:
    - verify nagios
    - reload nagios

- name: "conf:options: Remove options"
  ansible.builtin.lineinfile:
    backrefs: true
    dest: "{{ item.0.file }}"
    regexp: '^\s*#*\s*{{ item.1.key }}(.*)$'
    line: '# {{ item.1.key }}\g<1>'
    backup: "{{ bsd_nagios_backup_conf }}"
  loop: "{{ bsd_nagios_conf_options|subelements('conf') }}"
  loop_control:
    label: "{{ item.0.file }} {{ item.1.key }}"
  when: not item.1.present|default(true)|bool
  notify:
    - verify nagios
    - reload nagios

# EOF
...
