---
- name: "Conf:vars: Include vars from {{ item }}"
  ansible.builtin.include_vars: "{{ item }}"

- name: "Conf:vars: To bsd_nagios_objects add {{ item }}"
  ansible.builtin.set_fact:
    bsd_nagios_objects: "{{ bsd_nagios_objects + objects }}"

# EOF
