---

- name: "conf:files: Debug"
  debug:
    var: bsd_nagios_conf_files
  when: bsd_nagios_debug|bool

- name: "conf:files: Remove config files"
  file:
    path: "{{ item }}"
    state: absent
  loop: "{{ bsd_nagios_conf_files }}"
  when: bsd_nagios_conf_recreate|bool

- name: "conf:files: Create config files"
  include_tasks: conf/create_file.yml
  loop: "{{ bsd_nagios_conf_files }}"

# EOF
...
