---
- name: "Conf:options: Debug bsd_nagios_debug={{ bsd_nagios_debug }}"
  when: bsd_nagios_debug | bool
  ansible.builtin.debug:
    var: bsd_nagios_conf_options

- name: "Conf:options: Configure options"
  when: item.1.present | d(true)
  notify: [verify nagios, reload nagios]
  ansible.builtin.lineinfile:
    dest: "{{ item.0.file }}"
    regexp: ^\s*#*\s*{{ item.1.key }}
    line: "{{ item.1.key }}={{ item.1.val }}"
    backup: "{{ bsd_nagios_backup_conf }}"
  loop: "{{ bsd_nagios_conf_options | subelements('conf') }}"
  loop_control:
    label: "{{ item.0.file }} {{ item.1.key }}={{ item.1.val }}"

- name: "Conf:options: Remove options"
  when: not item.1.present | d(true)
  notify: [verify nagios, reload nagios]
  ansible.builtin.lineinfile:
    backrefs: true
    dest: "{{ item.0.file }}"
    regexp: ^\s*#*\s*{{ item.1.key }}(.*)$
    line: "# {{ item.1.key }}\\g<1>"
    backup: "{{ bsd_nagios_backup_conf }}"
  loop: "{{ bsd_nagios_conf_options | subelements('conf') }}"
  loop_control:
    label: "{{ item.0.file }} {{ item.1.key }}"

# EOF
